{
  "openapi": "3.0.0",
  "info": {
    "version": "1.0.0",
    "title": "오픈마켓 API",
    "description": "오픈마켓 API Server입니다."
  },
  "servers": [
    {
      "url": "https://localhost/api",
      "description": ""
    }
  ],
  "tags": [
    {
      "name": "회원",
      "description": "회원 관리 기능"
    },
    {
      "name": "상품",
      "description": "상품 관리 기능"
    },
    {
      "name": "주문",
      "description": "주문 관리 기능"
    },
    {
      "name": "후기",
      "description": "후기 관리 기능"
    },
    {
      "name": "파일",
      "description": "파일 관리 기능"
    }
  ],
  "paths": {
    "/users/": {
      "post": {
        "tags": [
          "회원"
        ],
        "summary": "회원 가입",
        "description": "회원 가입을 합니다.<br>회원 가입을 완료한 후 회원 정보를 반환합니다.",
        "responses": {
          "200": {
            "description": "성공",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CreateUserRes"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/CreateUserRes"
                }
              }
            }
          },
          "409": {
            "description": "이메일 중복",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error409"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error409"
                }
              }
            }
          },
          "422": {
            "description": "파라미터 검증 실패",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error422"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error422"
                }
              }
            }
          },
          "500": {
            "description": "서버 에러",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/Error500"
                }
              }
            }
          }
        },
        "requestBody": {
          "description": "회원 정보",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserReq"
              },
              "examples": {
                "기본 정보만 전달": {
                  "$ref": "#/components/examples/CreateUserReq"
                },
                "extra 속성 추가": {
                  "$ref": "#/components/examples/CreateUserReq1"
                }
              }
            }
          }
        }
      }
    },
    "/users/email": {
      "get": {
        "tags": [
          "회원"
        ],
        "summary": "이메일 중복 체크",
        "description": "이메일 중복을 체크 합니다.",
        "parameters": [
          {
            "name": "email",
            "description": "이메일",
            "in": "query",
            "required": true,
            "examples": {
              "someExample1": {
                "$ref": "#/components/examples/EmailDuplicate"
              }
            },
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "중복되지 않을 경우",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/EmailDuplicate"
                }
              },
              "application/xml": {
                "schema": {
                  "$ref": "#/components/schemas/EmailDuplicate"
                }
              }
            },
            "schema": {
              "$ref": "#/components/schemas/EmailNotDuplicate"
            }
          }
        }
      }
    },
    "/users/login": {
      "post": {
        "tags": [
          "회원"
        ],
        "summary": "로그인",
        "description": "",
        "parameters": [
          {
            "name": "email",
            "description": "가입할 회원 정보",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/UserInfo"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/users/refresh": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/users/{_id}/*": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/users/{_id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "patch": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/products/": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "minPrice",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "maxPrice",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "minDelivery",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "maxDelivery",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "seller_id",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "keyword",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "extra",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "seller_id": {
                    "example": "any"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/products/{_id}": {
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "patch": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "delete": {
        "description": "",
        "parameters": [
          {
            "name": "_id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/carts/": {
      "post": {
        "description": "",
        "responses": {
          "default": {
            "description": ""
          }
        }
      }
    },
    "/orders/": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "get": {
        "description": "",
        "parameters": [
          {
            "name": "keyword",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "extra",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort",
            "in": "query",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/replies/": {
      "post": {
        "description": "",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/codes/": {
      "post": {
        "description": "",
        "responses": {
          "default": {
            "description": ""
          }
        }
      }
    },
    "/files/": {
      "post": {
        "tags": [
          "파일"
        ],
        "summary": "파일 업로드",
        "description": "파일을 업로드 합니다.<br>회원 가입시 프로필 이미지를 첨부하거나 상품의 이미지를 미리 업로드 한 후 응답 받은 파일 경로를 사용하면 업로드한 파일에 접근이 가능합니다.<br>파일 업로드 완료 후 파일명과 경로를 반환합니다.",
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "attach": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "in": "header",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "Error422": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 0
          },
          "message": {
            "type": "string",
            "example": "잘못된 입력값이 있습니다."
          },
          "errors": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "example": "field"
                },
                "value": {
                  "type": "string",
                  "example": "swaggermarket.com"
                },
                "msg": {
                  "type": "string",
                  "example": "이메일 형식에 맞지 않습니다."
                },
                "path": {
                  "type": "string",
                  "example": "email"
                },
                "location": {
                  "type": "string",
                  "example": "body"
                }
              }
            }
          }
        },
        "xml": {
          "name": "Error422"
        }
      },
      "Error409": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 0
          },
          "message": {
            "type": "string",
            "example": "이미 등록되어 있는 이메일입니다."
          }
        },
        "xml": {
          "name": "Error409"
        }
      },
      "Error404": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 0
          },
          "message": {
            "type": "string",
            "example": "/api/user 리소스를 찾을 수 없습니다."
          }
        },
        "xml": {
          "name": "Error404"
        }
      },
      "Error500": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 0
          },
          "message": {
            "type": "string",
            "example": "요청하신 작업 처리에 실패했습니다. 잠시 후 다시 이용해 주시기 바랍니다."
          }
        },
        "xml": {
          "name": "Error500"
        }
      },
      "CreateUserReq": {
        "type": "object",
        "properties": {
          "email": {
            "type": "string",
            "example": "swagger@market.com"
          },
          "password": {
            "type": "string",
            "example": "12345678"
          },
          "name": {
            "type": "string",
            "example": "스웨거"
          },
          "phone": {
            "type": "string",
            "example": "01011112222"
          },
          "address": {
            "type": "string",
            "example": "서울시 강남구 역삼동 123"
          },
          "type": {
            "type": "string",
            "example": "user"
          }
        },
        "xml": {
          "name": "CreateUserReq"
        }
      },
      "CreateUserRes": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 1
          },
          "item": {
            "type": "object",
            "properties": {
              "email": {
                "type": "string",
                "example": "swagger@market.com"
              },
              "name": {
                "type": "string",
                "example": "스웨거"
              },
              "phone": {
                "type": "string",
                "example": "01011112222"
              },
              "address": {
                "type": "string",
                "example": "서울시 강남구 역삼동 123"
              },
              "type": {
                "type": "string",
                "example": "user"
              },
              "_id": {
                "type": "number",
                "example": 5
              },
              "createdAt": {
                "type": "string",
                "example": "2023.11.20 08:13:40"
              },
              "updatedAt": {
                "type": "string",
                "example": "2023.11.20 08:13:40"
              }
            }
          }
        },
        "xml": {
          "name": "CreateUserRes"
        }
      },
      "EmailDuplicate": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 1
          },
          "duplicate": {
            "type": "boolean",
            "example": true
          }
        },
        "xml": {
          "name": "EmailDuplicate"
        }
      },
      "EmailNotDuplicate": {
        "type": "object",
        "properties": {
          "ok": {
            "type": "number",
            "example": 1
          },
          "duplicate": {
            "type": "boolean",
            "example": false
          }
        },
        "xml": {
          "name": "EmailNotDuplicate"
        }
      }
    },
    "examples": {
      "CreateUserReq": {
        "value": {
          "email": "swagger@market.com",
          "password": "12345678",
          "name": "스웨거",
          "phone": "01011112222",
          "address": "서울시 강남구 역삼동 123",
          "type": "user"
        }
      },
      "CreateUserReq1": {
        "value": {
          "email": "swagger@market.com",
          "password": "12345678",
          "name": "스웨거",
          "phone": "01011112222",
          "address": "서울시 강남구 역삼동 123",
          "type": "user",
          "extra": {
            "gender": "extra에는 프로젝트에서 필요한 아무 속성이나",
            "age": "필요한 값을",
            "address": [
              "넣으면",
              "됩니다."
            ],
            "profileImage": "/uploads/swagger.jpg",
            "obj": {
              "hello": "객체로",
              "hi": "넣어도 됩니다."
            },
            "addressBook": [
              {
                "name": "집",
                "address": "서울시"
              },
              {
                "name": "회사",
                "address": "인천시"
              }
            ]
          }
        }
      },
      "CreateUserRes": {
        "value": {
          "ok": 1,
          "item": {
            "email": "swagger@market.com",
            "name": "스웨거",
            "phone": "01011112222",
            "address": "서울시 강남구 역삼동 123",
            "type": "user",
            "extra": {
              "gender": "아무 속성이나",
              "age": "필요한 값을",
              "address": [
                "넣으면",
                "됩니다."
              ],
              "profile": "/uploads/swagger.jpg",
              "obj": {
                "hello": "객체로",
                "hi": "넣어도 됩니다."
              }
            },
            "_id": 5,
            "createdAt": "2023.11.20 08:13:40",
            "updatedAt": "2023.11.20 08:13:40"
          }
        }
      }
    }
  }
}